runtime: python313

entrypoint: python app.py

env_variables:
  SECRET_KEY: "169a765d26005d18dcaf04d2453f37fb"
  GEMINI_API_KEY: "AIzaSyDM0L5w4-APrtv3T2t-ndbe8TDpU_sMngs"

handlers:
- url: /static
  static_dir: frontend
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
