steps:
  # Build container image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/studentflow:latest', '.']

  # Push image to Artifact/Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args: ['push', 'gcr.io/$PROJECT_ID/studentflow:latest']

  # Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run (Secret Manager)'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy studentflow \
          --image gcr.io/$PROJECT_ID/studentflow:latest \
          --region us-east1 \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets GEMINI_API_KEY=GEMINI_API_KEY:latest,SECRET_KEY=SECRET_KEY:latest

# No substitutions for secrets now; they are pulled from Secret Manager.
substitutions: {}

images:
  - 'gcr.io/$PROJECT_ID/studentflow:latest'

options:
  logging: CLOUD_LOGGING_ONLY
